/* automatically generated by rust-bindgen 0.63.0 */
// except that I had to guess at the type for size_t due to clang being uncooperative

extern "C" {
    pub fn demangle(
        res: *mut ::std::os::raw::c_char,
        bufsize: ::std::os::raw::c_ulong,
        mangled: *const ::std::os::raw::c_char,
    );
}
